### PR TITLE
FEAT: Add dll

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MementoRC** [comment]
@wolfv @Tobias-Fischer Turns out that it was an issue with the tabulation in GNUmakefile. The automated patching of conda-forge cannot handle tabulations, but Makefiles usually use tabulation as field separators. The solution adopted is to simply provide the patched file in the recipe files. Not that this is needed for windows since the name of the library is .dll and the .lib associated with it has its name set at creation (I am not knowledgeable with windows). A bit clunky, but it seems to work ... until we can test the .dll with `libquil` that I was thinking to work on next

**Comment by MementoRC** [comment]
The Travis flow puts jobs in queue that are never executed. Also, the latest build failed after the commit for linux-64 because the tests took too long to complete (or somehow hung then, but not here?), so it may be better (and much simpler) to remove the tests and perhaps keep an unmerged PR that implement the full flow with tests for peace of mind sake

**Comment by Tobias-Fischer** [comment]
Hi @MementoRC - again, many thanks for this; great work!

I don't like the vendored `Makefile` though, and as far as I know, there should not be an issue with spaces vs tabs, as long as the patch has been properly created. Perhaps we need to create the patch on Windows, so that the line endings match as well.

Maybe @traversaro knows more?

Thanks again!

**Comment by MementoRC** [comment]
Hi @Tobias-Fischer , I used `diff -Nu` to create the patch and it clearly was the tab indentation that threw it. I need to run an `expand -t x` to replace the tabs by space prior to patching. It is not an issue with tabs in a file though, as long as the patch does not target a line with tab. In that case it cannot find the reference line. The problem with the `Makefile` is that it needs a tab to identify  the target's actions

**Comment by traversaro** [comment]
> Maybe @traversaro knows more?

Yes, in theory patching should work fine if you correctly handle line endings. And indeed it seems that now it is working?

**Comment by MementoRC** [comment]
@traversaro conda patching of source does not seem handle tabulation well. I used `diff -Nu` to create the patch, I used to create the new file. The patch seems ok, but conda patching reports that the original file does not have the matching reference with the tab. The issue is make even more complex with windows

**Comment by MementoRC** [comment]
@Tobias-Fischer The win build completed by adding the needed target to the `Makefile` within the `bld.bat` - The Travis runs are very capricious and fail occasionally by not starting. I think it would be best to return to a cross-build for one of them (I think the aarch64 worked build well in cross)

**Pull request merged**
