### PR TITLE
osx-arm64 + osx on master branch

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Note: if this gets merged, we should delete the `osx` branch.

**Comment by Tobias-Fischer** [comment]
Seems like the newer versions require a newer glibc than what is available in conda-forge ..I'll skip roslisp for now on osx-arm64 @wolfv.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @wolfv - this is ready to be merged. Thanks!

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Friendly ping @wolfv - would be great if you could click merge :)

**Comment by Tobias-Fischer** [comment]
Hi @wolfv - seems like the automerge didn't to the job for some reason. Could you please manually click merge?

**Comment by wolfv** [comment]
Done! Sorry

**Pull request merged**
