### PR TITLE
FEAT: osx arm64 from source - WIP: This requires emulator or native build

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MementoRC** [comment]
The big problem is that building from source requires access to both host and target, since sbcl compiles itself in the build process. I think only a native build will work in this case

**Comment by MementoRC** [comment]
@xhochy Is there a way to have access to a native osx-arm64 machine? This recipe requires to have access to both host and targett

**Comment by Tobias-Fischer** [comment]
Hi @MementoRC - I don't think we need an emulator or native build. All we have to do is building those tools-for-build (at least `tools-for-build/grovel-headers`) for osx-64 instead of osx-arm64, so that it can run on the build machine. We do this in several places within conda-forge, e.g. https://github.com/conda-forge/gazebo-feedstock/blob/8a60c5a155a1660e42388cd06318dcfb30bc7c8b/recipe/build.sh#L1-L26

**Comment by MementoRC** [comment]
Right, initially that's what I tried, the endianness and info from grovel could be gathered in some way, but the build process is multi-stage, `sbcl` builds itself from LISP code in stage2. I don't know how important it is, i.e. I could try to patch the build process to be cross-compiled only (using the bootstrapping sbcl for stage2)

**Comment by MementoRC** [comment]
Obsolete

**Pull request closed without merging**
