### PR TITLE
FEAT: add windows

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
I don’t think we’re allowed binary distributed files in conda-forge, are we?

**Comment by MementoRC** [comment]
> I don’t think we’re allowed binary distributed files in conda-forge, are we?

Is it not already distributing the binaries for the other platform? Well, my end goal is to build from source, so I need a bootstrap. Since I don't have a windows )or mac), I need to use a PR to test, that's a bit annoying, with probably lots of email traffic :(

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin  please rerender

**Comment by MementoRC** [comment]
@Tobias-Fischer My apologies, I forgot to put this debugging PR. On the bright side, I think it is very close to be ready. I opened a new PR just for windows since I still struggle with linux

**Comment by Tobias-Fischer** [comment]
See #10 instead

**Pull request closed without merging**
