### PR TITLE
FEAT: build ppc64le from source

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MementoRC** [comment]
@xhochy At your convenience, this recipe builds but fails to set the test environment, any hints as to how to debug/resolve this? Note that I tried to cross-compile for a while, but I cannot figure out what the issue is, the cros-compilation fails in the middle of compiling with QEMU, SBCL feedback is that this is possibly an issue with QEMU

**Comment by MementoRC** [comment]
@BastianZim The issue was in trying to select glibc 2.28. Is it something missing in the `run` or `test/requires`? On the other hand, I was quite sure I needed 2.28 for linux64, maybe I should double-check.
Thanks for the help, your comments gave me just enough motivation to get over my resignation and continue digging

**Comment by BastianZim** [comment]
> The issue was in trying to select glibc 2.28. Is it something missing in the run or test/requires?

Oh, hmm I'm not sure on that one, but the feedstock owners are well-versed based on other projects I have seen. Maybe make it ready for review and ask them?

**Comment by MementoRC** [comment]
Yes, this was a trial and error PR, I will integrate it with the more robust PR for `aarch64`, it has more tests to validate that the build is correct. Thanks for the help.

Since no good deed ever goes unpunished, I have another question. For the same recipe, I am trying to provide an `osx_arm64` build, but I need an emulator (or a native build) to proceed but the `CROSSCOMPILING_EMULATOR` variable does not seem to be set for that cross-build, am I missing something?

**Comment by BastianZim** [comment]
I think, conda-forge can only cross compile macOS arm builds currently so native builds are out of the question. Could it be that it is not set because it doesn't emulate but cross compile?

**Comment by MementoRC** [comment]
@BastianZim right. could it be that the osx-x86_64 'understands' the osx-arm64 binary directly? In the PR I worked on, the cross-compiled build succeededwithout CROSSCOMPILING_EMULATOR. It should have failed (it failed with the other cross-compilation and I had to patch the source to integrate the emulator in its build flow) - is that what the 'universal' mode allows?

**Comment by MementoRC** [comment]
closing after merge into https://github.com/conda-forge/sbcl-feedstock/pull/14

**Pull request closed without merging**
