### PR TITLE
FEAT: build win arm64 from source

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MementoRC** [comment]
@isuruf At your convenience, could you take a look at this recipe? Is this recipe really working? `sbcl` is supposed to be compiling itself from the host, then recompile itself, thus executing a `src/runtime/sbcl` that is an ARM64 binary. I expected this build to fail, normally, I need to use the `CROSSCOMPILING_EMULATOR` for the other cross-compilation (linux-aarch64), I saw in https://github.com/conda-forge/conda-forge.github.io/issues/1126 that is was set, only to discover that it is not in this flow

**Comment by Tobias-Fischer** [comment]
Do you have an arm64 system on which you could test this on? In this case we could save the artefact so you could install it and see if it works

**Comment by MementoRC** [comment]
No, I don't, nor even a win system. I added it for sake of completeness - we could provide it candidly and await for an issue

**Comment by Tobias-Fischer** [comment]
Hi @traversaro - sorry to ping you and feel free to ignore. If you have interest in sbcl for win-arm64, do you want to take a look?

**Comment by MementoRC** [comment]
Outdated (already in the artifacts)

**Pull request closed without merging**
