### PR TITLE
FEAT: Update to latest compatible versions

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
awesome!

**Comment by Tobias-Fischer** [comment]
Happy to merge if you fix the sha256 sum on osx @MementoRC

**Comment by MementoRC** [comment]
Cool. Trying out the armhf binary on the arm64 because it is a more recent `2.3.3` version

**Comment by MementoRC** [comment]
Ok, so the issue is that I would prefer to have the latest 2.x.x version for all platforms, thus using the `armhf` binary for the `arm64` platform. but that binary has a interpreter set to `/lib/ld-linux-armhf.so.3: bad ELF interpreter: No such file or directory`. @xhochy would using patchelf to make the binary interpreter more generic work?

**Comment by MementoRC** [comment]
The idea was that `armhf` binaries are supposed to be executable on `arm64` (at least that's what I thought), but they likely have to be statically linked. SO leaving `aarch64` with v1.x.x.
@Tobias-Fischer Ready for review/merge

**Comment by Tobias-Fischer** [comment]
I am not sure what to do with the `build_number` here, as the linux-aarch64 version has not been bumped. I think it would be safer to set it to `2`?

**Comment by MementoRC** [comment]
Good point

**Pull request merged**
